In [3]:
import numpy as np

# from measure_island_size import add_clusters, estimate_diameter, plot_clusters
import measure_island_size
import filehandling
from order_parameters import add_translational_order
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib auto

Using matplotlib backend: Qt5Agg


In [2]:
directory = "/media/data/Data/BallBearing/HIPS/IslandExperiments/1,93mmRepeats"
files = filehandling.get_directory_filenames(f"{directory}/*.hdf5")
frames = []
for file in files:
    data = pd.read_hdf(file)
    data, lattice_vector = add_translational_order(data)
    frame = data.loc[0]
    diameter = estimate_diameter(frame[['x', 'y']].values)
    frame = add_clusters(frame.copy(), 0.1, 0.8, 2*diameter)
    frames.append(frame)


In [5]:
frames

[                 y            x        mass      size       ecc     signal  \
 frame                                                                        
 0        54.130286   651.828190  960.238174  1.793215  0.027690  64.015878   
 0        54.102404   679.278365  760.874439  1.797969  0.183266  52.310118   
 0        54.920284   699.939065  876.468825  1.854809  0.098241  55.968168   
 0        55.400842   719.780636  782.091130  1.784980  0.038049  54.504948   
 0        56.439768   739.749395  756.118974  1.664101  0.045406  69.137149   
 ...            ...          ...         ...       ...       ...        ...   
 0      1988.869093  1640.857686  673.447040  1.756960  0.073265  49.749483   
 0      1989.507508  1576.221722  730.878428  1.868419  0.143143  46.457237   
 0      1989.879400  1660.671091  633.940098  1.825162  0.040751  42.433382   
 0      1990.502924  1680.162573  625.526582  1.762176  0.039403  47.920457   
 0      1992.909346  1693.069159  782.822740  1.8499

In [6]:
cluster_sizes = [f.groupby('cluster').count().x.values for f in frames]

In [11]:
import numpy as np

In [7]:
cluster_sizes = np.concatenate(cluster_sizes)

In [8]:
%matplotlib auto
plt.hist(cluster_sizes, bins=100)

Using matplotlib backend: Qt5Agg


(array([1.6241e+05, 1.0037e+04, 3.5720e+03, 1.9340e+03, 1.2830e+03,
        8.9300e+02, 3.5100e+02, 5.8400e+02, 4.6600e+02, 4.0900e+02,
        3.3800e+02, 2.8200e+02, 1.1400e+02, 2.1000e+02, 2.0300e+02,
        1.2700e+02, 1.1300e+02, 1.2400e+02, 5.2000e+01, 9.7000e+01,
        6.9000e+01, 7.6000e+01, 6.4000e+01, 4.6000e+01, 1.8000e+01,
        4.2000e+01, 3.8000e+01, 3.4000e+01, 2.7000e+01, 2.3000e+01,
        1.9000e+01, 7.0000e+00, 1.9000e+01, 1.0000e+01, 9.0000e+00,
        4.0000e+00, 8.0000e+00, 6.0000e+00, 7.0000e+00, 3.0000e+00,
        3.0000e+00, 0.0000e+00, 2.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 0.0000e+00, 2.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 1.0000e+00, 0.0000e+00, 0.00

In [9]:
from scipy import spatial

In [12]:
def get_cluster_areas(df):
    if len(df) > 3:
        points = df[['x', 'y']].values
        hull = spatial.ConvexHull(points)
        return hull.volume  # in 2D volume is area
    else:
        return 0.0

In [13]:
areas = np.concatenate([f.groupby('cluster').apply(get_cluster_areas) for f in frames])

In [17]:
plt.hist(areas[areas != 0], bins=np.linspace(0, 10000, 100))

(array([1.930e+02, 1.000e+00, 3.200e+01, 3.004e+03, 8.900e+01, 1.388e+03,
        7.740e+02, 4.070e+02, 7.920e+02, 6.800e+01, 7.780e+02, 1.000e+02,
        4.400e+02, 3.500e+02, 1.340e+02, 4.100e+02, 4.700e+01, 3.950e+02,
        1.060e+02, 2.180e+02, 2.340e+02, 9.500e+01, 2.330e+02, 5.300e+01,
        2.090e+02, 1.030e+02, 1.200e+02, 1.550e+02, 4.700e+01, 1.750e+02,
        6.000e+01, 1.470e+02, 1.190e+02, 7.600e+01, 1.260e+02, 4.400e+01,
        1.080e+02, 5.300e+01, 1.020e+02, 7.400e+01, 4.400e+01, 9.000e+01,
        3.900e+01, 8.800e+01, 3.600e+01, 6.300e+01, 9.300e+01, 4.300e+01,
        1.010e+02, 3.700e+01, 6.200e+01, 5.000e+01, 6.200e+01, 5.700e+01,
        3.400e+01, 6.500e+01, 3.900e+01, 6.000e+01, 6.200e+01, 3.300e+01,
        5.000e+01, 3.500e+01, 6.400e+01, 4.100e+01, 4.200e+01, 5.300e+01,
        2.000e+01, 5.600e+01, 2.200e+01, 3.700e+01, 3.500e+01, 2.500e+01,
        3.000e+01, 2.500e+01, 3.400e+01, 3.000e+01, 3.300e+01, 3.200e+01,
        3.000e+01, 2.600e+01, 1.800e+0

In [18]:
import cv2

In [22]:
def get_cluster_rect(df):
    if len(df)>3:
        points = df[['x', 'y']].values
        hull = spatial.ConvexHull(points)

    else:
        return None
    return rect

In [23]:
rects = np.concatenate([f.groupby('cluster').apply(get_cluster_rect) for f in frames])

error: OpenCV(4.5.3) /tmp/pip-req-build-3umofm98/opencv/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'


In [38]:
def get_cluster_aspect(df):
    if len(df) > 2:
        xy = df[['x', 'y']].values.T
        eigvals, eigvecs = np.linalg.eig(np.cov(xy))
        plt.plot(df.x, df.y, 'o')
        center = xy.mean(axis=1)
        print(center)
        for val, vec in zip(eigvals, eigvecs.T):
            val *= 2
            x, y = np.vstack((center+val * vec, center-val * vec)).T
            plt.plot(x, y, 'b-', lw=2)

In [39]:
frames[0].groupby('cluster').apply(get_cluster_aspect)

[738.74680723  90.63753383]
[872.27355257  71.03147361]
[1195.45708961   68.12724217]
[1325.06928525  118.15434997]
[1472.34289553   83.29268211]
[1559.95462903   94.69339118]
[1595.4726782    94.47944153]
[1670.47933316   96.48923916]
[1180.11450002  102.28663825]
[1721.84928751  112.1641893 ]
[831.71119765 110.87824354]
[625.41587561 135.29883333]
[1470.78512926  144.46847019]
[1612.54405008  186.30960201]
[673.81067604 176.96318741]
[1155.14215358  150.97581548]
[1723.72387854  141.6101628 ]
[874.0436212  152.61078359]
[933.99336928 179.41726473]
[1687.70984032  184.1751692 ]
[806.94282853 201.00900601]
[1513.85199937  167.41851587]
[1060.99726682  173.67258604]
[1761.8038105   169.60332203]
[1668.14277175  189.44382754]
[1724.72051058  179.28545857]
[989.96555824 213.18202506]
[1052.79375024  201.29804759]
[1584.82475146  198.53978577]
[1780.74460314  193.81212792]
[599.0410946  190.48214157]
[1271.9573638   235.13654389]
[1383.43957239  203.20405579]
[1161.70878426  266.06565114]


Empty DataFrame
Columns: []
Index: []

In [41]:
for frame in frames:
    plt.figure()
    plot_clusters(frame)

<ipython-input-41-8a9d511fd16e>:2: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure()


In [42]:
plt.close('all')

In [6]:
plot_clusters(frames[0])

In [5]:
xdiameter

20.01864328901162

In [9]:
from scipy import spatial

In [124]:
import importlib
importlib.reload(measure_island_size)

<module 'measure_island_size' from '/home/ppxjd3/Code/Experiments/ball_bearings/1,95mm/measure_island_size.py'>

In [81]:
frame0 = measure_island_size.add_clusters(frames[0].copy(), 0.15, 0.8, 2*diameter)

In [68]:

measure_island_size.plot_clusters(frame0)

In [6]:
def get_ordered_clusters(df):
    hexatic_order = np.abs(np.mean(df.hexatic_order))
    count = len(df)
    if count > 3:
        hull = spatial.ConvexHull(df[['x', 'y']])
        area = hull.volume
    else:
        area = 0
    return hexatic_order > 0.8 and count > 3 and area > 1000
# frame0_hexatic = frame0.groupby('cluster').filter(get_ordered_clusters)

In [149]:
measure_island_size.plot_clusters(frame0_hexatic)

In [142]:
counts = frame0_hexatic.groupby('cluster').count().x.values
plt.hist(counts, bins=100)

(array([11.,  4.,  1.,  2.,  0.,  2.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,
         0.,  1.,  1.,  1.,  0.,  0.,  0.,  4.,  1.,  1.,  2.,  0.,  2.,
         0.,  3.,  4.,  2.,  0.,  1.,  1.,  0.,  1.,  2.,  3.,  2.,  2.,
         0.,  1.,  1.,  1.,  0.,  4.,  1.,  0.,  1.,  1.,  1.,  0.,  3.,
         3.,  0.,  1.,  0.,  2.,  2.,  1.,  0.,  4.,  3.,  2.,  1.,  1.,
         2.,  0.,  2.,  1.,  2.,  1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  3.,  3.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.]),
 array([ 4.  ,  4.85,  5.7 ,  6.55,  7.4 ,  8.25,  9.1 ,  9.95, 10.8 ,
        11.65, 12.5 , 13.35, 14.2 , 15.05, 15.9 , 16.75, 17.6 , 18.45,
        19.3 , 20.15, 21.  , 21.85, 22.7 , 23.55, 24.4 , 25.25, 26.1 ,
        26.95, 27.8 , 28.65, 29.5 , 30.35, 31.2 , 32.05, 32.9 , 33.75,
        34.6 , 35.45, 36.3 , 37.15, 38.  , 38.85, 39.7 , 40.55, 41.4 ,
        42.25, 43.1 , 43.95, 44.8 , 45.65, 46.5 , 47.35, 48.2 , 49.05,
        

In [12]:
def get_areas(df):
    hull = spatial.ConvexHull(df[['x', 'y']].values)
    return hull.volume

In [145]:
areas = frame0_hexatic.groupby('cluster').apply(get_areas)

In [81]:
directory = "/media/data/Data/BallBearing/HIPS/IslandExperiments/1,91mmRepeatsB"
files = filehandling.get_directory_filenames(f"{directory}/*.hdf5")
frames = []
for file in files:
    data = pd.read_hdf(file)
    data, lattice_vector = add_translational_order(data)
    frame = data.loc[0]
    diameter = measure_island_size.estimate_diameter(frame[['x', 'y']].values)
    frame = measure_island_size.add_clusters(frame.copy(), 0.15, 0.8, 2*diameter)
    # frame = frame.groupby('cluster').filter(get_ordered_clusters)
    frames.append(frame)

In [82]:
frames_filtered = [f.groupby('cluster').filter(get_ordered_clusters) for f in frames]

In [83]:
areas_stacked = [f.groupby('cluster').apply(get_areas) for f in frames_filtered]
print([len(a) for a in areas_stacked])
areas = np.concatenate([a for a in areas_stacked if len(a)])

[10, 15, 15, 13, 7, 10, 10, 12, 8, 11]


In [67]:
import cv2
def get_aspect_ratios(df):
    cnt = df[['x', 'y']].values.reshape((-1, 1, 2)).astype('int32')
    x, y, w, h = cv2.boundingRect(cnt)
    aspect = float(w)/h
    return aspect

def get_solidities(df):
    cnt = df[['x', 'y']].values.reshape((-1, 1, 2)).astype('int32')
    area = cv2.contourArea(cnt)
    hull = cv2.convexHull(cnt)
    hull_area = cv2.contourArea(hull)
    solidity = float(area)/hull_area
    return solidity

def get_ratio(df):
    cnt = df[['x', 'y']].values.reshape((-1, 1, 2)).astype('int32')
    (x, y), r = cv2.minEnclosingCircle(cnt)
    circle_area = np.pi * r**2
    hull = cv2.convexHull(cnt)
    hull_area = cv2.contourArea(hull)
    return hull_area/circle_area


In [61]:
solidities = [f.groupby('cluster').apply(get_solidities) for f in frames_filtered]
solidities = [s.values for s in solidities]
solidities = [item for sublist in solidities for item in sublist]

In [ ]:
aspect_ratios = [f.groupby('cluster').apply(get_aspect_ratios) for f in frames_filtered]
aspect_ratios = [a.values for a in aspect_ratios]
aspect_ratios = [item for sublist in aspect_ratios for item in sublist]

In [68]:
area_ratios = [f.groupby('cluster').apply(get_ratio) for f in frames_filtered]
area_ratios = [a.values for a in area_ratios]
area_ratios = [item for sublist in area_ratios for item in sublist]

In [74]:
plt.hist(area_ratios, bins=100)
plt.axvline(np.mean(area_ratios))

In [75]:
mean_aspect = np.mean(area_ratios)
std_aspect = np.std(area_ratios)
areas_aspected = [a for a, s in zip(areas, area_ratios) if mean_aspect-std_aspect < s < mean_aspect+std_aspect]

In [76]:
plt.hist(areas_aspected, bins=100)

(array([281., 182., 131., 175., 124., 142., 156., 126., 133., 152., 116.,
        120., 120.,  92.,  97.,  87.,  82.,  85.,  59.,  71.,  80.,  58.,
         59.,  32.,  52.,  32.,  26.,  26.,  31.,  18.,  25.,  21.,  18.,
         10.,  13.,  16.,  13.,   9.,  10.,   5.,   7.,   4.,   5.,   6.,
          4.,   2.,   3.,   4.,   5.,   1.,   3.,   0.,   2.,   4.,   1.,
          1.,   2.,   2.,   1.,   3.,   2.,   1.,   1.,   2.,   3.,   1.,
          1.,   2.,   0.,   1.,   1.,   1.,   0.,   0.,   1.,   0.,   0.,
          1.,   0.,   0.,   0.,   1.,   0.,   1.,   1.,   1.,   1.,   0.,
          1.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,
          1.]),
 array([ 1005.15587016,  1593.38028128,  2181.6046924 ,  2769.82910351,
         3358.05351463,  3946.27792575,  4534.50233686,  5122.72674798,
         5710.9511591 ,  6299.17557021,  6887.39998133,  7475.62439245,
         8063.84880356,  8652.07321468,  9240.29762579,  9828.52203691,
        10416.74644803, 11004.

In [84]:

plt.hist(areas, bins=100)

(array([9., 8., 2., 9., 7., 5., 3., 5., 9., 2., 2., 5., 1., 3., 3., 5., 1.,
        2., 1., 2., 4., 3., 2., 3., 2., 0., 2., 0., 0., 1., 0., 1., 0., 0.,
        2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.]),
 array([ 1002.89392679,  1131.75595458,  1260.61798237,  1389.48001016,
         1518.34203795,  1647.20406574,  1776.06609353,  1904.92812132,
         2033.79014911,  2162.6521769 ,  2291.51420469,  2420.37623247,
         2549.23826026,  2678.10028805,  2806.96231584,  2935.82434363,
         3064.68637142,  3193.54839921,  3322.410427  ,  3451.27245479,
         3580.13448258,  3708.99651037,  3837.85853816,  3966.72056595,
         4095.58259374,  4224.44462153,  4353.30664932,  4482.16867711,
         4611.0307049 ,  4739.89273269,  4868.

In [79]:
counts = np.concatenate([np.sqrt(f.groupby('cluster').count().x) for f in frames_filtered])

In [80]:
plt.hist(counts, bins=100)
plt.axvline(np.mean(counts))
plt.axvline(np.median(counts), c='red')

In [169]:
def hull_vertices_std(df):
    points = df[['x', 'y']].values
    hull = spatial.ConvexHull(points)
    center = points.mean(axis=0)
    vertices = hull.vertices
    vertices = np.append(vertices, vertices[0])
    vertices = points[vertices, :]
    vectors = vertices - center
    angles = np.arctan2(vectors[:, 1], vectors[:, 0])
    angle_diffs = np.abs(angles[1:] - angles[:-1])
    angle_diffs[angle_diffs>np.pi] -= np.pi
    return np.std(angle_diffs)

frames_angles = frames[0].groupby('cluster').apply(hull_vertices_std)

In [86]:
measure_island_size.plot_clusters(frames[5])
plt.title('1.91mm')

Text(0.5, 1.0, '1.91mm')

In [192]:
x = np.arange(1.85, 2.00, 0.01)
y = 0.57/(2-x)
plt.plot(x, y)
plt.xlabel('L [mm]')
plt.ylabel('Island Width')

Text(0, 0.5, 'Island Width')